# test: 
#   path: /test/{age<\d+>?0}
#   controller : App\Controller\TestController::test
#   # defaults : 
#   #   age : 0 
#   # requirements : 
#   #   age : \d+
#   methods : [GET, POST]
#   host : localhost
#   # host : {subdomain}.monsite.com
#   # autoriste www.monsite.com && api.monsite.com && monsite.com

#   schemes : [https]